// Generated by CoffeeScript 1.12.7
(function() {
  var coffee, compile;

  coffee = require('coffee-script');

  compile = function(options) {
    if (options == null) {
      options = {};
    }
    return function(src) {
      src = Buffer.from(src).toString('utf8');
      return Promise.resolve(coffee.compile(src, options));
    };
  };

  module.exports = {
    compile: compile
  };

}).call(this);
