// Generated by CoffeeScript 1.12.7
(function() {
  var coffee, compiler, express, fs, generate, middleware, path, pug, serve, stylus, util;

  fs = require('fs');

  pug = require('./pug');

  path = require('path');

  util = require('./util');

  coffee = require('./coffee');

  stylus = require('./stylus');

  express = require('./express');

  compiler = require('./compiler');

  generate = function(filename) {
    var ref;
    if (typeof filename === 'object' && ((ref = filename["arguments"]) != null ? ref.length : void 0) === 1) {
      filename = filename["arguments"][0];
    }
    return util.files.read(util.files.source(filename)).then(compiler(filename)).then(util.files.write(filename));
  };

  serve = express.serve, middleware = express.middleware;

  module.exports = {
    pug: pug,
    stylus: stylus,
    coffee: coffee,
    util: util,
    compiler: compiler,
    generate: generate,
    serve: serve,
    middleware: middleware
  };

}).call(this);
