// Generated by CoffeeScript 1.12.7
(function() {
  var compile, stylus;

  stylus = require('stylus');

  compile = function(options) {
    if (options == null) {
      options = {};
    }
    return function(src) {
      return new Promise(function(resolve, reject) {
        return stylus.render(src, options, function(err, css) {
          if (err != null) {
            return reject(err);
          }
          return resolve(css);
        });
      });
    };
  };

  module.exports = {
    compile: compile
  };

}).call(this);
